name: Mi workflow

# Cuando suceda qué
on: push

# Lo que queremos que suceda
jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código 
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aingerubeor/holamundo
