name: Mi workflow

# Cuando suceda qué
on:
  push:
    branches:
      - main

# Lo que queremos que suceda
jobs:
  test-os:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código 
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

  build_push:
    runs-on: ubuntu-latest
    # Indicamos las tareas previas
    needs: [test]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aingerubeor/holamundo
