name: Mi workflow

# Cuando suceda qué
on: push

# Lo que queremos que suceda
jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código 
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Crear imagen Docker
        run: docker build -t aingerubeor/holamundo .

      - name: Probar imagen
        run: docker run aingerubeor/holamundo
